bind_addr = ":8080"
log_level = "debug"
database_url = "host=localhost user=postgres password=maxim dbname=hotel_service sslmode=disable"
session_key = "UqLTN5uCX0BRSme4YQHo9artw1OWdsVhIx3fFpZP7ijJz86nG2EAblKkDygcvM"